front:
    resource: ../../src/Controller/FrontController.php
    type: annotation
search:
    resource: ../../src/Controller/SearchController.php
    type: annotation
libraries:
    resource: ../../src/Controller/LibraryController.php
    type: annotation
services:
    resource: ../../src/Controller/ServiceController.php
    type: annotation
jsonld:
    resource: ../../src/Controller/JsonLdController.php
    type: annotation
footer:
    resource: ../../src/Controller/FooterController.php
    type: annotation
sitemap:
    resource: ../../src/Controller/SiteMapController.php
    type: annotation
redirects:
    resource: ../../src/Controller/RedirectController.php
    type: annotation
